export const BUILTIN_PROVIDER_ICON_NAMES = [
  "claude",
  "codex",
  "copilot",
  "kiro",
  "minimax",
  "omp",
  "opencode",
  "pi",
];

export const ACP_PROVIDER_ICON_NAMES = [
  "agoragentic-acp",
  "amp-acp",
  "auggie",
  "autohand",
  "cline",
  "codebuddy-code",
  "codewhale",
  "cortex-code",
  "corust-agent",
  "crow-cli",
  "cursor",
  "deepagents",
  "dimcode",
  "dirac",
  "factory-droid",
  "fast-agent",
  "gemini",
  "gjc",
  "glm-acp-agent",
  "goose",
  "grok",
  "junie",
  "kilo",
  "kimi",
  "minimax-code",
  "minion-code",
  "mistral-vibe",
  "nova",
  "poolside",
  "qoder",
  "qwen-code",
  "sigit",
  "stakpak",
  "traecli",
  "vtcode",
];

export const TERMINAL_PROFILE_ICON_NAMES = ["agy"];

export const KNOWN_PROVIDER_ICON_NAMES = [
  ...BUILTIN_PROVIDER_ICON_NAMES,
  ...ACP_PROVIDER_ICON_NAMES,
  ...TERMINAL_PROFILE_ICON_NAMES,
];
