import type { TextStyle, ViewStyle } from "react-native";

/** Move parent-facing geometry to the host; keep the text's box and typography together. */
export function hostTextStyle(style: TextStyle) {
  const {
    alignSelf,
    aspectRatio,
    bottom,
    display,
    end,
    flex,
    flexBasis,
    flexGrow,
    flexShrink,
    height,
    left,
    margin,
    marginBottom,
    marginEnd,
    marginHorizontal,
    marginLeft,
    marginRight,
    marginStart,
    marginTop,
    marginVertical,
    maxHeight,
    maxWidth,
    minHeight,
    minWidth,
    position,
    right,
    start,
    top,
    width,
    zIndex,
    ...text
  } = style;
  const host: ViewStyle = {
    alignSelf,
    aspectRatio,
    bottom,
    display,
    end,
    flex,
    flexBasis,
    flexGrow,
    flexShrink,
    height,
    left,
    margin,
    marginBottom,
    marginEnd,
    marginHorizontal,
    marginLeft,
    marginRight,
    marginStart,
    marginTop,
    marginVertical,
    maxHeight,
    maxWidth,
    minHeight,
    minWidth,
    position,
    right,
    start,
    top,
    width,
    zIndex,
  };
  return { host, text };
}
